# Site settings
title: nuewmn blog
email: nuewmn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog about Python, Machine learning, C++,  
  a bit about math, cryptograpy and iformation security. 
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nuewmn.github.io" # the base hostname & protocol for your site
twitter_username: nuewmn
github_username:  nuewmn

# Build settings
markdown: kramdown

paginate: 4

author: nuewmn

gems: [jekyll-paginate]
